baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'Enlight Fragments'

disableKinds = ["taxonomy", "term"]

[sitemap]
  disable = true

[taxonomies]
  category = "categories"
  tag = "tags"

[outputs]
  home = ['html', 'rss']


[outputFormats.RSS]
mediatype = "application/rss"
baseName = "rss"
